add

diff --git a/.github/workflows/repository_size.yml b/.github/workflows/repository_size.yml
--- a/.github/workflows/repository_size.yml
+++ b/.github/workflows/repository_size.yml
@@ -17,7 +17,10 @@ jobs:
       - run: |
           check.sh $(pwd) $(pwd)
           if [ -f coding-style-reports.log ]; then
-            cat coding-style-reports.log
+            while IFS= read -r line; do
+              echo "::error file=${{github.workspace}}/${line#* }::${line}"
+            done < coding-style-reports.log
+            exit 1
           fi
 
   check_program_compilation:
